live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#3e4452"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#be5046"
white = "#5c6370"
yellow = "#d19a66"

[colors.cursor]
cursor = "#528bff"
text = "#0b0b0b"

[colors.normal]
black = "#24272e"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#abb2bf"
yellow = "#e5c07b"

[colors.primary]
background = "#24272e"
foreground = "#abb2bf"

# [colors.search."colors.footer_bar"]
# background = "#282c34"
# foreground = "#abb2bf"

[colors.search.matches]
background = "#e5c07b"
foreground = "#3e4452"

[colors.selection]
background = "#3e4452"
text = "#abb2bf"

[colors.vi_mode_cursor]
cursor = "#333841"
text = "#abb2bf"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "Full"
dynamic_padding = true
startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
